
AnchorLayout:
	anchor_x:"center"
	anchor_y:"top"
	MainMenu:


<MainMenu>:
	pos_hint:{"top":0.7}
	size_hint: 0.5 , 0.7
	orientation:"vertical"
	Button:
		name:"play_btn"
		font_size:50
		on_release: app.root.current = "game_selection_screen"
		text:"Play"

	Button:
		name:"tools_btn"
		text:"Tools"
		on_release: app.root.current = "tools_screen"

	Button:
		text:"Exit"
		name:"exit_btn"
		on_release:app.stop()
